[package]
name = "reuters"
version = "0.1.0"
edition = "2021"

[dependencies]
rouille = { version = "3.5", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
maud = "0.23"
cached = { version = "0.32", default-features = false, features = ["proc_macro"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
ureq = { version = "2.4", features = ["json", "tls", "rustls"] }
rustls = { version = "0.20", default-features = false }
rustls-native-certs = "0.6"
lazy_static = "1.4"

[build-dependencies]
grass = "0.10.8"
glob = "0.3.0"

[profile.release]
strip = true
opt-level = 3
lto = "fat"
panic = "abort"
debug = false
codegen-units = 1
