name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://rust:alpine
    - name: Install musl-gcc
      run: sudo apt -y install musl-tools
    - name: Install musl rust target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build Release
      run: cargo build --release --target x86_64-unknown-linux-musl --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: neuters
        path: target/x86_64-unknown-linux-musl/release/neuters
